# Sourced by EVERY zsh: login, interactive, scripts, `zsh -c`.
# Pure environment only — no PATH (path_helper reorders it later), no output.

# Homebrew hardening (see README.md)
# Authority is the root-owned /etc/homebrew/brew.env, deployed from
# ~/scripts/brew.env (with HOMEBREW_SYSTEM_ENV_TAKES_PRIORITY it overrides
# shell env for every brew run, including the autoupdate launchd job);
# these shell copies are for visibility and non-brew tooling.

export HOMEBREW_UPDATE_TO_TAG=1                      # Brew itself follows stable release tags only
export HOMEBREW_VERIFY_ATTESTATIONS=1                # Verify bottle build provenance (sigstore, needs gh)
export HOMEBREW_NO_INSECURE_REDIRECT=1               # Refuse HTTPS->HTTP download redirects
export HOMEBREW_FORBID_PACKAGES_FROM_PATHS=1         # No installs from local paths (brew install ./x.rb)
export HOMEBREW_NO_ANALYTICS=1                       # No analytics
export HOMEBREW_CASK_OPTS="--require-sha"            # Refuse casks without a real checksum (sha256 :no_check)
export HOMEBREW_FORMULA_BUILD_NETWORK=deny           # Sandbox: no network during source builds
export HOMEBREW_FORMULA_POSTINSTALL_NETWORK=deny     # Sandbox: no network during postinstall
export HOMEBREW_FORMULA_TEST_NETWORK=deny            # Sandbox: no network during brew test
export HOMEBREW_ALLOWED_TAPS="homebrew/core homebrew/cask homebrew/autoupdate buildpacks/tap forwardimpact/tap microsoft/apm oven-sh/bun supabase/tap"

# Compiler search paths
export CPATH="/opt/homebrew/include${CPATH:+:$CPATH}"
export LIBRARY_PATH="/opt/homebrew/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"

# Runtime environments
export NODE_USE_SYSTEM_CA=1                          # Node/Bun trust the macOS keychain (Zscaler TLS inspection)

# CA bundle exported from the macOS keychains (Apple roots + corp CAs) so
# Python ssl/urllib, uv/uvx and pipx (uv backend) trust the TLS inspection
# chain; pip>=24.2 reads the keychain itself. Generated by the
# 50-ca-bundle bootstrap hook; rerun `make bootstrap` after a CA rotation.
[ -f "$HOME/.config/ssl/ca-bundle.pem" ] && export SSL_CERT_FILE="$HOME/.config/ssl/ca-bundle.pem"

# Bitwarden SSH agent (from Homebrew or Apple App Store)
export SSH_AUTH_SOCK="$HOME/.bitwarden-ssh-agent.sock"
#export SSH_AUTH_SOCK="$HOME/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
